### PR TITLE
Update plugin for UA SDK 7.1.2

### PR DESCRIPTION
**Pull request by rlepinski**
This is a rather large rewrite of the plugin to integrate with the latest Urban Airship SDK. I moved the majority of the integration into an AirshipReceiver to make it integrate easier into existing UA installations.

Other Changes:
- Normalized the code style to match Android minus the Hungarian notation
- Cleaned up tracked build files
- Cleaned up manifest. Only the AirshipReceiver is required.
- Pull dependencies from bintray instead of the AAR.
- Fragment now only uses custom events for reporting. Makes the action no longer needed. If you want to add custom events through the landing page use "add_custom_event_action" instead of the redefined adenda action.

TODO:
- There is no license in this repo. Can we add one? Apache version 2?
- The setup guide is out of date now.
- We can make this easier to integrate if we could pull down the adenda aar from a maven repo. We could this host this plugin and make it a 1 line integration.
- Since this allows notifications to be displayed with the lock screen fragment, we might want to dismiss the notification and lockscreen if one of them is interacted with. I could not figure out how to dismiss the adenda fragment without dismissing all of them. Help is needed.
- Testing.

### CODE REVIEW

**Comment by fdoumet** [comment]
Thanks for this! I added mechanisms to:
- dismiss the lock screen fragment if the the notification was clicked on
- dismiss the notification as soon as the lock screen fragment is loaded

But how do you configure a message through the message composer to be sent without an alert? I tried sending one with an In-App message, or with neither an In-App message nor a Notification, but in both cases the Landing Page was never sent down with the payload (`LandingPageAction` is just null when trying to retrieve it in `AirshipReceiver`)

**Comment by rlepinski** [comment]
My mistake. Looks like the composer does not allow this. Ill update to include a factory. I still think we should keep the factory as simple as possible so its more of an optional change. Ill try to update today.

**Comment by fdoumet** [comment]
Yes, we could define a Custom Key to include as part of the push that determines whether or not the notification is displayed. Branch with my additions [here](https://github.com/adenda/adenda-urbanairship/tree/pr/1).

**Comment by rlepinski** [comment]
@fdoumet thanks!

I cherry-picked your change and fixed my merge conflict. I think its ready to go but I have not tested it fully.

**Comment by rlepinski** [comment]
Actually going to add a flag to ignore/show notification

**Comment by fdoumet** [comment]
Merged into master from [pr/2](https://github.com/adenda/adenda-urbanairship/tree/pr/2)

**Pull request closed without merging**
